# Generated by Django 5.2.1 on 2025-05-29 04:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_rename_post_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='body',
            new_name='content',
        ),
        migrations.AddField(
            model_name='entry',
            name='chapter',
            field=models.CharField(choices=[('aftertaste', 'Aftertaste'), ('dev notes', 'Dev Notes'), ('other ramblings', 'Other Ramblings'), ('primeengine', 'Prime Engine')], default='default content', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
