# Generated by Django 5.2.1 on 2025-05-29 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_rename_body_entry_content_entry_chapter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='chapter',
            field=models.CharField(choices=[('aftertaste', 'Aftertaste'), ('devnotes', 'Dev Notes'), ('otherramblings', 'Other Ramblings'), ('primeengine', 'Prime Engine')], max_length=50),
        ),
    ]
