# Generated by Django 6.0 on 2026-01-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_alter_entry_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='chapter',
            field=models.CharField(choices=[('nighttongue', 'NightTongue'), ('devnotes', 'Dev Notes'), ('otherramblings', 'Other Ramblings'), ('primeengine', 'Prime Engine')], max_length=50),
        ),
    ]
