# Generated by Django 6.0 on 2026-01-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_alter_entry_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
