# Generated by Django 6.0 on 2026-01-16 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_entry_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['order', '-created_at']},
        ),
    ]
